#!/bin/sh

curl -s "127.0.0.1:8000/user" | jq -r .Users[].HomeDir | xargs -I {} cp /opt/lomorage/var/assets.db {}
sudo apt-get update
sudo apt-get --only-upgrade install -y lomo-base lomo-backend lomo-web lomo-frame
